export const MOCK_PRODUCTS = [
  {
    id: '1', name: 'Slate Frost T-Shirt', slug: 'slate-frost-t-shirt',
    description: 'Premium minimalist t-shirt featuring a subtle mountain graphic, inspired by frosted alpine slate.',
    shortDesc: 'Minimalist mountain tee in slate grey',
    basePrice: 499, comparePrice: 599, sku: 'WM-TS-001',
    tags: ['t-shirt', 'slate', 'minimal', 'mountain'],
    isActive: true, isFeatured: true, totalStock: 150, avgRating: 4.5, reviewCount: 24,
    images: [{ id: '1', url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v1', name: 'S', size: 'S', stock: 25, isActive: true },
      { id: 'v2', name: 'M', size: 'M', stock: 40, isActive: true },
      { id: 'v3', name: 'L', size: 'L', stock: 35, isActive: true },
      { id: 'v4', name: 'XL', size: 'XL', stock: 20, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '2', name: 'Alpine Cabin T-Shirt', slug: 'alpine-cabin-t-shirt',
    description: 'High-quality deep forest green t-shirt, crafted for the cozy mountain lifestyle.',
    shortDesc: 'Forest green with cabin graphic',
    basePrice: 499, sku: 'WM-TS-002',
    tags: ['t-shirt', 'forest', 'green'],
    isActive: true, isFeatured: true, totalStock: 120, avgRating: 4.2, reviewCount: 18,
    images: [{ id: '2', url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v5', name: 'S', size: 'S', stock: 20, isActive: true },
      { id: 'v6', name: 'M', size: 'M', stock: 35, isActive: true },
      { id: 'v7', name: 'L', size: 'L', stock: 30, isActive: true },
      { id: 'v8', name: 'XL', size: 'XL', stock: 15, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '3', name: 'Glacier White T-Shirt', slug: 'glacier-white-t-shirt',
    description: 'Crisp white premium t-shirt, essential minimal wear for any outdoor journey.',
    shortDesc: 'Essential white tee with peak detail',
    basePrice: 499, comparePrice: 549, sku: 'WM-TS-003',
    tags: ['t-shirt', 'white', 'essential'],
    isActive: true, isFeatured: true, totalStock: 200, avgRating: 4.8, reviewCount: 42,
    images: [{ id: '3', url: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v9', name: 'S', size: 'S', stock: 30, isActive: true },
      { id: 'v10', name: 'M', size: 'M', stock: 50, isActive: true },
      { id: 'v11', name: 'L', size: 'L', stock: 45, isActive: true },
      { id: 'v12', name: 'XL', size: 'XL', stock: 25, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '4', name: 'Peak Seeker Black T-Shirt', slug: 'peak-seeker-black-t-shirt',
    description: 'Bold black t-shirt with minimalist peak design for the adventurous soul.',
    shortDesc: 'Bold black with peak design',
    basePrice: 549, sku: 'WM-TS-004',
    tags: ['t-shirt', 'black', 'bold'],
    isActive: true, isFeatured: true, totalStock: 180, avgRating: 4.6, reviewCount: 31,
    images: [{ id: '4', url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v13', name: 'S', size: 'S', stock: 25, isActive: true },
      { id: 'v14', name: 'M', size: 'M', stock: 45, isActive: true },
      { id: 'v15', name: 'L', size: 'L', stock: 40, isActive: true },
      { id: 'v16', name: 'XL', size: 'XL', stock: 20, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '5', name: 'Summit Grey T-Shirt', slug: 'summit-grey-t-shirt',
    description: 'Versatile grey tee with subtle mountain silhouette, perfect for any occasion.',
    shortDesc: 'Versatile grey with mountain silhouette',
    basePrice: 499, sku: 'WM-TS-005',
    tags: ['t-shirt', 'grey', 'versatile'],
    isActive: true, totalStock: 160, avgRating: 4.3, reviewCount: 15,
    images: [{ id: '5', url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v17', name: 'S', size: 'S', stock: 20, isActive: true },
      { id: 'v18', name: 'M', size: 'M', stock: 40, isActive: true },
      { id: 'v19', name: 'L', size: 'L', stock: 35, isActive: true },
      { id: 'v20', name: 'XL', size: 'XL', stock: 15, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '6', name: 'Forest Trail Olive T-Shirt', slug: 'forest-trail-olive-t-shirt',
    description: 'Earthy olive green tee inspired by mountain trails and forest paths.',
    shortDesc: 'Earthy olive with trail graphic',
    basePrice: 499, sku: 'WM-TS-006',
    tags: ['t-shirt', 'olive', 'trail'],
    isActive: true, totalStock: 90, avgRating: 4.1, reviewCount: 9,
    images: [{ id: '6', url: 'https://images.unsplash.com/photo-1608236415053-f7f5d5b76af6?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v21', name: 'S', size: 'S', stock: 15, isActive: true },
      { id: 'v22', name: 'M', size: 'M', stock: 25, isActive: true },
      { id: 'v23', name: 'L', size: 'L', stock: 20, isActive: true },
      { id: 'v24', name: 'XL', size: 'XL', stock: 10, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '7', name: 'Alpine Navy T-Shirt', slug: 'alpine-navy-t-shirt',
    description: 'Classic navy blue with clean mountain graphics, timeless and elegant.',
    shortDesc: 'Classic navy with mountain graphics',
    basePrice: 499, sku: 'WM-TS-007',
    tags: ['t-shirt', 'navy', 'classic'],
    isActive: true, totalStock: 140, avgRating: 4.4, reviewCount: 22,
    images: [{ id: '7', url: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v25', name: 'S', size: 'S', stock: 20, isActive: true },
      { id: 'v26', name: 'M', size: 'M', stock: 35, isActive: true },
      { id: 'v27', name: 'L', size: 'L', stock: 30, isActive: true },
      { id: 'v28', name: 'XL', size: 'XL', stock: 15, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '8', name: 'Misty Morning Cream T-Shirt', slug: 'misty-morning-cream-t-shirt',
    description: 'Soft cream colored tee capturing the essence of misty mountain mornings.',
    shortDesc: 'Soft cream capturing misty mornings',
    basePrice: 549, sku: 'WM-TS-008',
    tags: ['t-shirt', 'cream', 'soft'],
    isActive: true, isFeatured: true, totalStock: 75, avgRating: 4.7, reviewCount: 12,
    images: [{ id: '8', url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v29', name: 'S', size: 'S', stock: 10, isActive: true },
      { id: 'v30', name: 'M', size: 'M', stock: 20, isActive: true },
      { id: 'v31', name: 'L', size: 'L', stock: 15, isActive: true },
      { id: 'v32', name: 'XL', size: 'XL', stock: 5, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '9', name: 'Trailblazer Hoodie', slug: 'trailblazer-hoodie',
    description: 'Premium heavyweight hoodie with embroidered mountain logo. French terry cotton with a brushed interior for ultimate warmth.',
    shortDesc: 'Premium heavyweight hoodie',
    basePrice: 599, comparePrice: 699, sku: 'WM-HD-001',
    tags: ['hoodie', 'premium', 'heavyweight'],
    isActive: true, isFeatured: true, totalStock: 60, avgRating: 4.9, reviewCount: 8,
    images: [{ id: '9', url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v33', name: 'S', size: 'S', stock: 10, isActive: true },
      { id: 'v34', name: 'M', size: 'M', stock: 20, isActive: true },
      { id: 'v35', name: 'L', size: 'L', stock: 15, isActive: true },
      { id: 'v36', name: 'XL', size: 'XL', stock: 8, isActive: true },
    ],
    categories: [{ category: { id: 'c2', name: 'Hoodies', slug: 'hoodies' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '10', name: 'Summit Cap', slug: 'summit-cap',
    description: 'Clean structured cap with embroidered peak logo. Adjustable strap and premium cotton twill construction.',
    shortDesc: 'Structured cap with peak logo',
    basePrice: 299, sku: 'WM-AC-001',
    tags: ['cap', 'accessory', 'structured'],
    isActive: true, isFeatured: true, totalStock: 120, avgRating: 4.3, reviewCount: 14,
    images: [{ id: '10', url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v37', name: 'One Size', size: 'OS', stock: 120, isActive: true },
    ],
    categories: [{ category: { id: 'c3', name: 'Accessories', slug: 'accessories' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '11', name: 'Canvas Trail Tote', slug: 'canvas-trail-tote',
    description: 'Heavyweight canvas tote with mountain motif print. Reinforced stitching and spacious interior for everyday carry.',
    shortDesc: 'Heavyweight canvas tote',
    basePrice: 399, comparePrice: 449, sku: 'WM-AC-002',
    tags: ['tote', 'canvas', 'accessory'],
    isActive: true, isFeatured: true, totalStock: 80, avgRating: 4.5, reviewCount: 6,
    images: [{ id: '11', url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v38', name: 'One Size', size: 'OS', stock: 80, isActive: true },
    ],
    categories: [{ category: { id: 'c3', name: 'Accessories', slug: 'accessories' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '12', name: 'Midnight Black Hoodie', slug: 'midnight-black-hoodie',
    description: 'Sleek black pullover hoodie with tonal mountain embroidery. Ultra-soft fleece interior for maximum comfort.',
    shortDesc: 'Sleek black pullover hoodie',
    basePrice: 649, sku: 'WM-HD-002',
    tags: ['hoodie', 'black', 'fleece'],
    isActive: true, isFeatured: true, totalStock: 45, avgRating: 4.7, reviewCount: 11,
    images: [{ id: '12', url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v39', name: 'S', size: 'S', stock: 8, isActive: true },
      { id: 'v40', name: 'M', size: 'M', stock: 15, isActive: true },
      { id: 'v41', name: 'L', size: 'L', stock: 12, isActive: true },
      { id: 'v42', name: 'XL', size: 'XL', stock: 5, isActive: true },
    ],
    categories: [{ category: { id: 'c2', name: 'Hoodies', slug: 'hoodies' } }],
    reviews: [],
    relatedProducts: [],
  },
  {
    id: '13', name: 'Ridge Runner Heather Tee', slug: 'ridge-runner-heather-tee',
    description: 'Soft heather grey tee with a bold mountain ridge graphic across the chest. Pre-shrunk cotton for lasting fit.',
    shortDesc: 'Heather grey with ridge graphic',
    basePrice: 449, sku: 'WM-TS-009',
    tags: ['t-shirt', 'heather', 'ridge', 'graphic'],
    isActive: true, isFeatured: true, totalStock: 100, avgRating: 4.4, reviewCount: 19,
    images: [{ id: '13', url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80', isPrimary: true, sortOrder: 0 }],
    variants: [
      { id: 'v43', name: 'S', size: 'S', stock: 15, isActive: true },
      { id: 'v44', name: 'M', size: 'M', stock: 30, isActive: true },
      { id: 'v45', name: 'L', size: 'L', stock: 25, isActive: true },
      { id: 'v46', name: 'XL', size: 'XL', stock: 10, isActive: true },
    ],
    categories: [{ category: { id: 'c1', name: 'T-Shirts', slug: 't-shirts' } }],
    reviews: [],
    relatedProducts: [],
  },
];
